//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int ID_Продажи { get; set; }
        public int ID_Заказа { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
        public decimal Общая_сумма { get; set; }
    
        public virtual Заказы Заказы { get; set; }
    }
}
