//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_заказа
    {
        public int ID_Состава { get; set; }
        public int ID_Заказа { get; set; }
        public int ID_Номенклатуры { get; set; }
        public decimal Количество { get; set; }
        public decimal Цена_на_момент_заказа { get; set; }
        public decimal Сумма_позиций { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Номенклатура Номенклатура { get; set; }
    }
}
